Name=input("ENTER Name")
Branch=input("enter Branch")
gender=input("enter gender")
college=input("enter college")
age=int(input("enter age"))
print(Name,Name)
print(Branch,Branch)
print(gender,gender)
print(college,college)
print(age,age)
